#include "Easing.h"
#include <sstream>
#include <unordered_map>

using namespace weave;
using namespace weave::easing;



//Helper macros to create a table of named references to functions
#define macroTable(n) {#n, weave::easing::n},

//Returns an easing function given its name
easing::EasingCurve weave::easing::GetEasingFunction(std::string const &name) {
	static std::unordered_map<std::string, weave::easing::EasingCurve> map = {
		macroTable(linear)
		macroTable(flat)
		macroTable(step)
		macroTable(sin)
		macroTable(cos)
		macroTable(bounceIn)
		macroTable(bounceOut)
		macroTable(bounceInOut)
		macroTable(circIn)
		macroTable(circInOut)
		macroTable(circOut)
		macroTable(cubicElasticIn)
		macroTable(cubicElasticOut)
		macroTable(cubicIn)
		macroTable(cubicInOut)
		macroTable(cubicOut)
		macroTable(elasticHardIn)
		macroTable(elasticHardOut)
		macroTable(elasticSoftIn)
		macroTable(elasticSoftOut)
		macroTable(expIn)
		macroTable(expInOut)
		macroTable(expOut)
		macroTable(quadraticIn)
		macroTable(quadraticInOut)
		macroTable(quadraticOut)
		macroTable(quarticElasticIn)
		macroTable(quarticElasticOut)
		macroTable(quarticIn)
		macroTable(quarticInOut)
		macroTable(quarticOut)
		macroTable(quinticIn)
		macroTable(quinticInOut)
		macroTable(quinticOut)
		macroTable(sinusIn)
		macroTable(sinusInOut)
		macroTable(sinusOut)

		//Inverted
		macroTable(ilinear)
		macroTable(istep)
		macroTable(isin)
		macroTable(icos)
		macroTable(ibounceIn)
		macroTable(ibounceOut)
		macroTable(ibounceInOut)
		macroTable(icircIn)
		macroTable(icircInOut)
		macroTable(icircOut)
		macroTable(icubicElasticIn)
		macroTable(icubicElasticOut)
		macroTable(icubicIn)
		macroTable(icubicInOut)
		macroTable(icubicOut)
		macroTable(ielasticHardIn)
		macroTable(ielasticHardOut)
		macroTable(ielasticSoftIn)
		macroTable(ielasticSoftOut)
		macroTable(iexpIn)
		macroTable(iexpInOut)
		macroTable(iexpOut)
		macroTable(iquadraticIn)
		macroTable(iquadraticInOut)
		macroTable(iquadraticOut)
		macroTable(iquarticElasticIn)
		macroTable(iquarticElasticOut)
		macroTable(iquarticIn)
		macroTable(iquarticInOut)
		macroTable(iquarticOut)
		macroTable(iquinticIn)
		macroTable(iquinticInOut)
		macroTable(iquinticOut)
		macroTable(isinusIn)
		macroTable(isinusInOut)
		macroTable(isinusOut)

		//Reflected
		macroTable(rlinear)
		macroTable(rstep)
		macroTable(rsin)
		macroTable(rcos)
		macroTable(rbounceIn)
		macroTable(rbounceOut)
		macroTable(rbounceInOut)
		macroTable(rcircIn)
		macroTable(rcircInOut)
		macroTable(rcircOut)
		macroTable(rcubicElasticIn)
		macroTable(rcubicElasticOut)
		macroTable(rcubicIn)
		macroTable(rcubicInOut)
		macroTable(rcubicOut)
		macroTable(relasticHardIn)
		macroTable(relasticHardOut)
		macroTable(relasticSoftIn)
		macroTable(relasticSoftOut)
		macroTable(rexpIn)
		macroTable(rexpInOut)
		macroTable(rexpOut)
		macroTable(rquadraticIn)
		macroTable(rquadraticInOut)
		macroTable(rquadraticOut)
		macroTable(rquarticElasticIn)
		macroTable(rquarticElasticOut)
		macroTable(rquarticIn)
		macroTable(rquarticInOut)
		macroTable(rquarticOut)
		macroTable(rquinticIn)
		macroTable(rquinticInOut)
		macroTable(rquinticOut)
		macroTable(rsinusIn)
		macroTable(rsinusInOut)
		macroTable(rsinusOut)

		//Reflected / Inverted
		macroTable(rilinear)
		macroTable(ristep)
		macroTable(risin)
		macroTable(ricos)
		macroTable(ribounceIn)
		macroTable(ribounceOut)
		macroTable(ribounceInOut)
		macroTable(ricircIn)
		macroTable(ricircInOut)
		macroTable(ricircOut)
		macroTable(ricubicElasticIn)
		macroTable(ricubicElasticOut)
		macroTable(ricubicIn)
		macroTable(ricubicInOut)
		macroTable(ricubicOut)
		macroTable(rielasticHardIn)
		macroTable(rielasticHardOut)
		macroTable(rielasticSoftIn)
		macroTable(rielasticSoftOut)
		macroTable(riexpIn)
		macroTable(riexpInOut)
		macroTable(riexpOut)
		macroTable(riquadraticIn)
		macroTable(riquadraticInOut)
		macroTable(riquadraticOut)
		macroTable(riquarticElasticIn)
		macroTable(riquarticElasticOut)
		macroTable(riquarticIn)
		macroTable(riquarticInOut)
		macroTable(riquarticOut)
		macroTable(riquinticIn)
		macroTable(riquinticInOut)
		macroTable(riquinticOut)
		macroTable(risinusIn)
		macroTable(risinusInOut)
		macroTable(risinusOut)
	};

	auto const &it = map.find(name);
	return (it != map.end() ? it->second : linear);
}

#undef macroTable