#include "RayPicking.h"
#include "Geometry.h"

using namespace weave;
using namespace weave::algebra;
using namespace raypicking;

//Returns the position on the Z = 0 plane of the picking ray generated by the normalized window coordinates
Ray weave::raypicking::pickingRay(weave::Matrix4x4 const &unprojection, weave::Matrix4x4 const &invCamera, float cursorx, float cursory) {
	//Create two points with the cursor supplied, one located on the near plane and another on the far plane and apply the unprojection, including the projection division
	vec4 znear = unprojection * vec4(cursorx, cursory, 0.0f, 1.0f);
	vec4 zfar = unprojection * vec4(cursorx, cursory, 1.0f, 1.0f);
	znear /= (znear.w);
	zfar /= (zfar.w);

	//Apply the inverse camera transform to put the points in world space
	znear = invCamera * znear;
	zfar = invCamera * zfar;

	//Tracing a line between znear and zfar, find the point that hits the z=0 plane
	Ray ray;
	ray.direction = zfar.xyz - znear.xyz;
	ray.origin = znear.xyz - ray.direction * (znear.z / ray.direction.z);

	return ray;
}

PickResult weave::raypicking::pickSphere(Ray const& ray, Vector3 const& spherePosition, float sphereRadius)
{
	//Ray is defined as P = p + tv
	//where P = point(s) of collision, p = the origin of the ray and v = the direction vector. t is a scalar that determines the movement along the vector.
	//t is what we are looking for; at what t values the ray collides with the sphere.

	//At any P or P' point where the ray hits the sphere we know that the length of the vector between the center of the sphere and P is equal to its radius, so:
	// |P - center| ^ 2 = r^2

	//Placing the ray equation in this formula we can eventually extract a quadratic function and solve for t:
	//(P-center)*(P-center) - r^2 = 0
	//(p+tv - c)*(p+tv - c) - r2 = 0 --> develop --> t^2(v*v) + 2tv*(p-c) + (p-c)*(p-c) - r^2 = 0 --> solve for t such as At^2 + Bt + C = 0
	//Details here: http://wiki.cgsociety.org/index.php/Ray_Sphere_Intersection
	PickResult result;
	Vector3 pmc = ray.direction - spherePosition; //p - c

	float A2 = 2 * dot(ray.direction, ray.direction);
	float B = 2 * dot(ray.direction, pmc);
	float C = dot(pmc, pmc) - sphereRadius * sphereRadius;

	float n = B * B - 2 * A2 * C; //This goes inside the sqrt. If this is negative, the ray isn't touching the sphere at all
	if (n < 0.0f || A2 == 0.0f) {
		return result;
	}

	//These are the two solutions for the system
	float rootn = std::sqrtf(n);
	float t0 = (-B + rootn) / A2;
	float t1 = (-B - rootn) / A2;

	//Swap them so that t1 is always the biggest value (aka, the second hit)
	if (t0 > t1)
		std::swap(t0, t1);

	//If t0 and t1 < 0 means the ray hits the sphere but only if we extend it behind the origin, thus it's not hitting the sphere.
	//If t1 is negative, both are negative
	if (t1 < 0) {
		return result;
	}

	//Select the smallest value higher than 0 as the valid solution
	float t = (t0 < 0 ? t1 : t0);

	//If this is being used for collision detection on a segment any value of t > rayLength means there's no hit
	if (isSegment(ray) && t > ray.length) {
		return result;
	}

	result.pointAlongRay = t;
	result.surfaceNormal = algebra::normalize(pointAlongRay(ray, t) - spherePosition);

	return result;
}

PickResult weave::raypicking::pickBox(Ray const& ray, Transform const& boxTransform, Vector3 const& boxHalfSize)
{
	//Box is not axis aligned, so first we transform the ray into box space so we can use it as an axis aligned box
	Matrix4x4 const& boxInvTrans = boxTransform.GetInverseTransformMatrixOrtho();
	Vector3 rayObj = boxInvTrans.TransformNormal(ray.direction);
	Vector3 rayObjInv = Vector3(1 / (rayObj.x + std::numeric_limits<float>::min()), 1 / (rayObj.y + std::numeric_limits<float>::min()), 1 / (rayObj.z + std::numeric_limits<float>::min()));
	Vector3 originObj = boxInvTrans * ray.origin;

	//Get the minimum and maximum corners of the box. Notice we use the box corners in box space, not world space
	Vector3 minCorner { -boxHalfSize.x, -boxHalfSize.y, -boxHalfSize.z };
	Vector3 maxCorner { +boxHalfSize.x, +boxHalfSize.y, +boxHalfSize.z };

	//Find the point on the ray where all 6 faces of the box are crossed
	auto tminCorner = (minCorner - originObj) * rayObjInv;
	auto tmaxCorner = (maxCorner - originObj) * rayObjInv;

	//Find the earliest and latest hit point
	float tmin = algebra::maxof(algebra::mincomps(tminCorner, tmaxCorner));
	float tmax = algebra::minof(algebra::maxcomps(tminCorner, tmaxCorner));

	//If the maximum point of collision is negative, the ray hits the box behind it, so it's not a collision. If tmin is the highest value, it's not a collision at all
	PickResult result;
	if (tmax < 0 || tmin > tmax || (isSegment(ray) && tmin > ray.length)) {
		return result;
	}

	//Ray intersects at the lowest positive between tmin and tmax
	result.pointAlongRay = (tmin >= 0.0f ? tmin : tmax);

	//Figure out the side we hit
	if      (result.pointAlongRay == tminCorner.x) result.surfaceNormal.Set(-1.0f, 0.0f, 0.0f);
	else if (result.pointAlongRay == tmaxCorner.x) result.surfaceNormal.Set(1.0f, 0.0f, 0.0f);
	else if (result.pointAlongRay == tminCorner.y) result.surfaceNormal.Set(0.0f, -1.0f, 0.0f);
	else if (result.pointAlongRay == tmaxCorner.y) result.surfaceNormal.Set(0.0f, 1.0f, 0.0f);
	else if (result.pointAlongRay == tminCorner.z) result.surfaceNormal.Set(0.0f, 0.0f, -1.0f);
	else if (result.pointAlongRay == tmaxCorner.z) result.surfaceNormal.Set(0.0f, 0.0f, 1.0f);

	//Convert the normal to world coordinates
	result.surfaceNormal = boxTransform.GetTransformMatrix().TransformNormal(result.surfaceNormal);

	return result;
}

std::pair<PickResult, bool> weave::raypicking::pickFrustum(Ray const& ray, Plane const frustumPlanes[6], bool exitOnFirstHit)
{
	//Check the ray's origin against each plane. If the origin lies outside any of the planes check the collision point with that plane.
	//If the collision point lies within the frustum, it's a hit. If the ray is inside the frustum, it's also a hit.
	//Plane / Ray intersection algorithm: http://en.wikipedia.org/wiki/Line-plane_intersection
	PickResult result;
	bool inside = false; 
	float best_t = std::numeric_limits<float>::max();
	Vector3 best_normal;

	for (unsigned int i = 0; i < 6; ++i) {
		Plane const& plane = frustumPlanes[i];

		if (geometry::distancePointToPlane(ray.origin, plane) > 0) {
			inside = true;
			Vector3 p0 = plane.xyz * plane.w;

			float denom = dot(p0 - ray.origin, plane.xyz);
			float numer = dot(ray.direction, plane.xyz);
			float t;
			//Check if the denominator is 0 first
			if (fabs(denom) < std::numeric_limits<float>::min()) {
				//Ray is parallel
				continue;
			}
			else {
				//Find the collision point
				t = denom / numer;

				//t must be positive for the ray to be hitting the plane. If the ray is a segment, t must be also smaller than length
				if (t < 0.0f || (isSegment(ray) && t > ray.length)) {
					//It doesn't hit the plane at all, so it can't be hitting the frustum on this plain
					continue;
				}

				//t must be lower than an already found solution or we aren't interested in it as we already know the ray hits
				if (t >= best_t)
					continue;

				//Check that the collision point is within the frustum bounds
				Vector3 hit = ray.origin + ray.direction * t;
				bool doesHit = true;
				for (unsigned j = 0; j < 6; ++j) {
					if (j == i)
						continue;

					if (geometry::distancePointToPlane(hit, frustumPlanes[j]) > 0) {
						//Hit point is outside one of the planes, it can't be hitting the frustum so we can ignore the point entirely
						doesHit = false;
						break;
					}
				}

				if (doesHit) {
					//Keep the smallest valid t as an answer
					best_t = t;
					best_normal = plane.xyz;
					//The ray is hitting a side of the frustum, we can conclude it hits the frustum and exit early if asked for
					if (exitOnFirstHit) {
						result.pointAlongRay = best_t;
						result.surfaceNormal = best_normal;
						return { result, inside };
					}
				}

				//Hit was outside the frustum space so we continue the checks against the planes
			}
		}
	}

	//Ray intersects at best_t
	if (best_t < std::numeric_limits<float>::max()) {
		result.pointAlongRay = best_t;
		result.surfaceNormal = best_normal;
	}

	return { result, inside };
}
