#include "ImageLoader.h"

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning(disable: 4100) //4100:  'ri': unreferenced formal parameter (Generated by stb)  
#pragma warning(disable: 4244) //4244: conversion from 'int' to 'stbi_uc', possible loss of data (Generated by stb)  
#endif

#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
#endif

#define STB_IMAGE_IMPLEMENTATION
#include "weave/system/external/stb/stb_image.h"
#undef STB_IMAGE_IMPLEMENTATION

#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#ifdef _MSC_VER
#pragma warning(pop)
#endif

//DDS and other helper definitions
namespace {

	//Swaps endianness of 64bit values
	inline void SwapEndian(uint64_t* data, uint32_t count) {
		for (uint64_t i = 0; i < count; ++i) {
			uint64_t x = *data;
			*data = (x << 56) | ((x & 0xFF00ul) << 40) | ((x & 0xFF0000ul) << 24) | ((x & 0xFF000000) << 8) |
				((x & 0xFF00000000ul) >> 8) | ((x & 0xFF0000000000ul) >> 24) | ((x & 0xFF0000000000ul) >> 40) | (x >> 56);
			++data;
		}
	}

	//Swaps endianness of 32bit values
	inline void SwapEndian(uint32_t* data, uint32_t count) {
		for (uint32_t i = 0; i < count; ++i) {
			uint32_t x = *data;
			*data = (x << 24) | ((x & 0xFF00) << 8) | ((x & 0xFF0000) >> 8) | (x >> 24);
			++data;
		}
	}

	//Swap endianness of 16bit values
	inline void SwapEndian(uint16_t* data, uint32_t count) {
		for (uint16_t i = 0; i < count; ++i) {
			uint16_t x = *data;
			*data = (x << 8) | (x >> 8);
			++data;
		}
	}

	inline uint32_t FOURCC(char a, char b, char c, char d) {
		return ((uint32_t)((uint32_t)(a)) | ((uint32_t)(b) << 8) | ((uint32_t)(c) << 16) | ((uint32_t)(d) << 24));
	}

	inline uint32_t FOURCC(uint32_t cc) {
		const uint32_t mask = 0xFF;
		return (cc >> 24) | (cc & (mask << 16)) >> 8 | (cc & (mask << 8)) << 8 | ((cc << 24));
	}

	//Header of a TGA file
	struct TGAHeader {
		uint8_t identlength;
		uint8_t colormaptype;
		uint8_t datatype;

		uint8_t b1, b2, b3, b4, b5;  //bytes a 0 en una TGA-24/32. Representa la info del Mapa de Color.

		uint16_t originx, originy, width, height;
		uint8_t bitsperpixel;

		uint8_t info;
	};


	//'MB' is the value of the magic number, but it could cause portability issues if used directly
	constexpr const uint32_t bmpMask = 19778U; //'MB'


	//Header of a BMP file
	struct BMPFileHeader {
		uint16_t    type;
		uint32_t   fileSize;
		uint16_t    r1;
		uint16_t    r2;
		uint32_t   offset;
	};

	//Second header of a BMP file
	struct BMPInfoHeader {
		uint32_t      headerSize;
		uint32_t       width;
		uint32_t       height;
		uint16_t       planes;
		uint16_t       bitsperpixel;
		uint32_t      compression;
		uint32_t      imageSize;
		uint32_t       pixelspermeterX;
		uint32_t       pixelspermeterY;
		uint32_t      colorsUsed;
		uint32_t      colorsImportant;
	};


	//Full BMP file header
	struct BMPHeader {
		BMPFileHeader h1;
		BMPInfoHeader h2;
	};

	//DDS related enums
	enum DDS_COMPRESSION_TYPE
	{
		DDS_COMPRESS_NONE = 0,
		DDS_COMPRESS_BC1, /* DXT1 */
		DDS_COMPRESS_BC2, /* DXT3 */
		DDS_COMPRESS_BC3, /* DXT5 */
		DDS_COMPRESS_BC3N, /* DXT5n */
		DDS_COMPRESS_BC4, /* ATI1 */
		DDS_COMPRESS_BC5, /* ATI2 */
		DDS_COMPRESS_AEXP, /* DXT5 */
		DDS_COMPRESS_YCOCG, /* DXT5 */
		DDS_COMPRESS_YCOCGS, /* DXT5 */
		DDS_COMPRESS_MAX
	};

	//DDS Pixel Format flags
	enum DDSD_FLAGS {
		DDSD_CAPS = 0x1,
		DDSD_HEIGHT = 0x2,
		DDSD_WIDTH = 0x4,
		DDSD_PITCH = 0x8,
		DDSD_PIXELFORMAT = 0x1000,
		DDSD_MIPMAPCOUNT = 0x20000,
		DDSD_LINEARSIZE = 0x80000,
		DDSD_DEPTH = 0x800000
	};

	enum DDPF_FLAGS {
		DDPF_ALPHAPIXELS = 0x00000001,
		DDPF_ALPHA = 0x00000002,
		DDPF_FOURCC = 0x00000004,
		DDPF_PALETTEINDEXED8 = 0x00000020,
		DDPF_RGB = 0x00000040,
		DDPF_LUMINANCE = 0x00020000
	};

	enum DDSCAPS_FLAGS {
		DDSCAPS_COMPLEX = 0x00000008,
		DDSCAPS_TEXTURE = 0x00001000,
		DDSCAPS_MIPMAP = 0x00400000,

		DDSCAPS2_CUBEMAP = 0x00000200,
		DDSCAPS2_CUBEMAP_POSITIVEX = 0x00000400,
		DDSCAPS2_CUBEMAP_NEGATIVEX = 0x00000800,
		DDSCAPS2_CUBEMAP_POSITIVEY = 0x00001000,
		DDSCAPS2_CUBEMAP_NEGATIVEY = 0x00002000,
		DDSCAPS2_CUBEMAP_POSITIVEZ = 0x00004000,
		DDSCAPS2_CUBEMAP_NEGATIVEZ = 0x00008000,
		DDSCAPS2_VOLUME = 0x00200000,

		DDSCAPS2_FULLCUBEMAP = 0x0000FE00
	};

	//DDS DX10 extensions enums
	enum DXGI_FORMAT {
		DXGI_FORMAT_UNKNOWN = 0,
		DXGI_FORMAT_R32G32B32A32_TYPELESS = 1,
		DXGI_FORMAT_R32G32B32A32_FLOAT = 2,
		DXGI_FORMAT_R32G32B32A32_UINT = 3,
		DXGI_FORMAT_R32G32B32A32_SINT = 4,
		DXGI_FORMAT_R32G32B32_TYPELESS = 5,
		DXGI_FORMAT_R32G32B32_FLOAT = 6,
		DXGI_FORMAT_R32G32B32_UINT = 7,
		DXGI_FORMAT_R32G32B32_SINT = 8,
		DXGI_FORMAT_R16G16B16A16_TYPELESS = 9,
		DXGI_FORMAT_R16G16B16A16_FLOAT = 10,
		DXGI_FORMAT_R16G16B16A16_UNORM = 11,
		DXGI_FORMAT_R16G16B16A16_UINT = 12,
		DXGI_FORMAT_R16G16B16A16_SNORM = 13,
		DXGI_FORMAT_R16G16B16A16_SINT = 14,
		DXGI_FORMAT_R32G32_TYPELESS = 15,
		DXGI_FORMAT_R32G32_FLOAT = 16,
		DXGI_FORMAT_R32G32_UINT = 17,
		DXGI_FORMAT_R32G32_SINT = 18,
		DXGI_FORMAT_R32G8X24_TYPELESS = 19,
		DXGI_FORMAT_D32_FLOAT_S8X24_UINT = 20,
		DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS = 21,
		DXGI_FORMAT_X32_TYPELESS_G8X24_UINT = 22,
		DXGI_FORMAT_R10G10B10A2_TYPELESS = 23,
		DXGI_FORMAT_R10G10B10A2_UNORM = 24,
		DXGI_FORMAT_R10G10B10A2_UINT = 25,
		DXGI_FORMAT_R11G11B10_FLOAT = 26,
		DXGI_FORMAT_R8G8B8A8_TYPELESS = 27,
		DXGI_FORMAT_R8G8B8A8_UNORM = 28,
		DXGI_FORMAT_R8G8B8A8_UNORM_SRGB = 29,
		DXGI_FORMAT_R8G8B8A8_UINT = 30,
		DXGI_FORMAT_R8G8B8A8_SNORM = 31,
		DXGI_FORMAT_R8G8B8A8_SINT = 32,
		DXGI_FORMAT_R16G16_TYPELESS = 33,
		DXGI_FORMAT_R16G16_FLOAT = 34,
		DXGI_FORMAT_R16G16_UNORM = 35,
		DXGI_FORMAT_R16G16_UINT = 36,
		DXGI_FORMAT_R16G16_SNORM = 37,
		DXGI_FORMAT_R16G16_SINT = 38,
		DXGI_FORMAT_R32_TYPELESS = 39,
		DXGI_FORMAT_D32_FLOAT = 40,
		DXGI_FORMAT_R32_FLOAT = 41,
		DXGI_FORMAT_R32_UINT = 42,
		DXGI_FORMAT_R32_SINT = 43,
		DXGI_FORMAT_R24G8_TYPELESS = 44,
		DXGI_FORMAT_D24_UNORM_S8_UINT = 45,
		DXGI_FORMAT_R24_UNORM_X8_TYPELESS = 46,
		DXGI_FORMAT_X24_TYPELESS_G8_UINT = 47,
		DXGI_FORMAT_R8G8_TYPELESS = 48,
		DXGI_FORMAT_R8G8_UNORM = 49,
		DXGI_FORMAT_R8G8_UINT = 50,
		DXGI_FORMAT_R8G8_SNORM = 51,
		DXGI_FORMAT_R8G8_SINT = 52,
		DXGI_FORMAT_R16_TYPELESS = 53,
		DXGI_FORMAT_R16_FLOAT = 54,
		DXGI_FORMAT_D16_UNORM = 55,
		DXGI_FORMAT_R16_UNORM = 56,
		DXGI_FORMAT_R16_UINT = 57,
		DXGI_FORMAT_R16_SNORM = 58,
		DXGI_FORMAT_R16_SINT = 59,
		DXGI_FORMAT_R8_TYPELESS = 60,
		DXGI_FORMAT_R8_UNORM = 61,
		DXGI_FORMAT_R8_UINT = 62,
		DXGI_FORMAT_R8_SNORM = 63,
		DXGI_FORMAT_R8_SINT = 64,
		DXGI_FORMAT_A8_UNORM = 65,
		DXGI_FORMAT_R1_UNORM = 66,
		DXGI_FORMAT_R9G9B9E5_SHAREDEXP = 67,
		DXGI_FORMAT_R8G8_B8G8_UNORM = 68,
		DXGI_FORMAT_G8R8_G8B8_UNORM = 69,
		DXGI_FORMAT_BC1_TYPELESS = 70,
		DXGI_FORMAT_BC1_UNORM = 71,
		DXGI_FORMAT_BC1_UNORM_SRGB = 72,
		DXGI_FORMAT_BC2_TYPELESS = 73,
		DXGI_FORMAT_BC2_UNORM = 74,
		DXGI_FORMAT_BC2_UNORM_SRGB = 75,
		DXGI_FORMAT_BC3_TYPELESS = 76,
		DXGI_FORMAT_BC3_UNORM = 77,
		DXGI_FORMAT_BC3_UNORM_SRGB = 78,
		DXGI_FORMAT_BC4_TYPELESS = 79,
		DXGI_FORMAT_BC4_UNORM = 80,
		DXGI_FORMAT_BC4_SNORM = 81,
		DXGI_FORMAT_BC5_TYPELESS = 82,
		DXGI_FORMAT_BC5_UNORM = 83,
		DXGI_FORMAT_BC5_SNORM = 84,
		DXGI_FORMAT_B5G6R5_UNORM = 85,
		DXGI_FORMAT_B5G5R5A1_UNORM = 86,
		DXGI_FORMAT_B8G8R8A8_UNORM = 87,
		DXGI_FORMAT_B8G8R8X8_UNORM = 88,
		DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM = 89,
		DXGI_FORMAT_B8G8R8A8_TYPELESS = 90,
		DXGI_FORMAT_B8G8R8A8_UNORM_SRGB = 91,
		DXGI_FORMAT_B8G8R8X8_TYPELESS = 92,
		DXGI_FORMAT_B8G8R8X8_UNORM_SRGB = 93,
		DXGI_FORMAT_BC6H_TYPELESS = 94,
		DXGI_FORMAT_BC6H_UF16 = 95,
		DXGI_FORMAT_BC6H_SF16 = 96,
		DXGI_FORMAT_BC7_TYPELESS = 97,
		DXGI_FORMAT_BC7_UNORM = 98,
		DXGI_FORMAT_BC7_UNORM_SRGB = 99,
		DXGI_FORMAT_AYUV = 100,
		DXGI_FORMAT_Y410 = 101,
		DXGI_FORMAT_Y416 = 102,
		DXGI_FORMAT_NV12 = 103,
		DXGI_FORMAT_P010 = 104,
		DXGI_FORMAT_P016 = 105,
		DXGI_FORMAT_420_OPAQUE = 106,
		DXGI_FORMAT_YUY2 = 107,
		DXGI_FORMAT_Y210 = 108,
		DXGI_FORMAT_Y216 = 109,
		DXGI_FORMAT_NV11 = 110,
		DXGI_FORMAT_AI44 = 111,
		DXGI_FORMAT_IA44 = 112,
		DXGI_FORMAT_P8 = 113,
		DXGI_FORMAT_A8P8 = 114,
		DXGI_FORMAT_B4G4R4A4_UNORM = 115,
		DXGI_FORMAT_B8G8R8_UNORM = 116,
		DXGI_FORMAT_R8G8B8_UNORM = 117,
		DXGI_FORMAT_FORCE_UINT = 0xffffffffUL
	};

	enum D3D10_RESOURCE_DIMENSION {
		D3D10_RESOURCE_DIMENSION_UNKNOWN = 0,
		D3D10_RESOURCE_DIMENSION_BUFFER = 1,
		D3D10_RESOURCE_DIMENSION_TEXTURE1D = 2,
		D3D10_RESOURCE_DIMENSION_TEXTURE2D = 3,
		D3D10_RESOURCE_DIMENSION_TEXTURE3D = 4
	};

	//DDS header structure
#define DDS_MAGICuint16_t 0x20534444

	struct DDSPixelFormat {
		uint32_t dwSize;
		uint32_t dwFlags;
		uint32_t dwFourCC;
		uint32_t dwRGBBitCount;
		uint32_t dwRBitMask;
		uint32_t dwGBitMask;
		uint32_t dwBBitMask;
		uint32_t dwABitMask;
	};

	struct DDSHeader {
		uint32_t           dwSize;
		uint32_t           dwFlags;
		uint32_t           dwHeight;
		uint32_t           dwWidth;
		uint32_t           dwPitchOrLinearSize;
		uint32_t           dwDepth;
		uint32_t           dwMipMapCount;
		uint32_t           dwReserved1[11];
		DDSPixelFormat ddspf;
		uint32_t           dwCaps;
		uint32_t           dwCaps2;
		uint32_t           dwCaps3;
		uint32_t           dwCaps4;
		uint32_t           dwReserved2;
	};

	//Extended DX10 header structure
	struct DDSHeaderDXT10 {
		DXGI_FORMAT              dxgiFormat;
		D3D10_RESOURCE_DIMENSION resourceDimension;
		uint32_t                 miscFlag;
		uint32_t                 arraySize;
		uint32_t                 reserved;
	};

	//KTX header structure
	//Format info:https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/
	struct KTXHeader {
		uint8_t identifier[12]; //'«', 'K', 'T', 'X', ' ', '1', '1', '»', '\r', '\n', '\x1A', '\n'
		uint32_t endianness;
		uint32_t glType;
		uint32_t glTypeSize;
		uint32_t glFormat;
		uint32_t glInternalFormat;
		uint32_t glBaseInternalFormat;
		uint32_t pixelWidth;
		uint32_t pixelHeight;
		uint32_t pixelDepth;
		uint32_t numberOfArrayElements;
		uint32_t numberOfFaces;
		uint32_t numberOfMipmapLevels;
		uint32_t bytesOfKeyValueData;
	};


	//Figure out a matching VkFormat from the DDS headers
	weave::vulkan::ImageFormat GetFormatFromDDS(DDSHeader const& header, DDSHeaderDXT10 const& headerDX10) {
		weave::vulkan::ImageFormat format = {};

		//Check for S3TC compressed texture
		if (header.ddspf.dwFlags & DDPF_FOURCC) {
			//Find the compresion format
			if (header.ddspf.dwFourCC == FOURCC('D','X','T','1')) {
				format = weave::vulkan::ImageFormat::BC1_RGB_UNORM_BLOCK;
			}
			else if (header.ddspf.dwFourCC == FOURCC('D','X','T','3')) {
				format = weave::vulkan::ImageFormat::BC2_UNORM_BLOCK;
			}
			else if (header.ddspf.dwFourCC == FOURCC('D','X','T','5')) {
				format = weave::vulkan::ImageFormat::BC3_UNORM_BLOCK;
			}

			else if (header.ddspf.dwFourCC == FOURCC('A','T','I','2')) {
				format = weave::vulkan::ImageFormat::BC5_UNORM_BLOCK;
			}
			else if (headerDX10.dxgiFormat == DXGI_FORMAT_BC6H_UF16) {
				format = weave::vulkan::ImageFormat::BC6H_UFLOAT_BLOCK;
			}
			else if (headerDX10.dxgiFormat == DXGI_FORMAT_BC6H_SF16) {
				format = weave::vulkan::ImageFormat::BC6H_SFLOAT_BLOCK;
			}
			else if (headerDX10.dxgiFormat == DXGI_FORMAT_BC7_UNORM_SRGB) {
				format = weave::vulkan::ImageFormat::BC7_SRGB_BLOCK;
			}
			else if (headerDX10.dxgiFormat == DXGI_FORMAT_BC7_UNORM) {
				format = weave::vulkan::ImageFormat::BC7_UNORM_BLOCK;
			}
		}
		//Check for uncompressed data
		else if (!(header.ddspf.dwFlags & DDPF_PALETTEINDEXED8) && header.ddspf.dwRGBBitCount >= 8) {
			uint32_t bcmps = header.ddspf.dwRGBBitCount / 8;

			//Determine type of image
			if (bcmps == 4) {
				//Check which flags are up to identify the correct type
				if (header.ddspf.dwRBitMask && header.ddspf.dwGBitMask && header.ddspf.dwBBitMask && header.ddspf.dwABitMask)
					format = weave::vulkan::ImageFormat::B8G8R8A8_UNORM;
				else if (header.ddspf.dwRBitMask && header.ddspf.dwGBitMask && header.ddspf.dwBBitMask) {
					if (header.ddspf.dwRBitMask == 0xff0000 && header.ddspf.dwGBitMask == 0xff00 && header.ddspf.dwBBitMask == 0xff) {
						format = weave::vulkan::ImageFormat::B8G8R8A8_UNORM;
					}
					else if (header.ddspf.dwRBitMask == 0x3ff && header.ddspf.dwGBitMask == 0xffc00 && header.ddspf.dwBBitMask == 0x3ff00000) {
						//type = DXGI_FORMAT_R10G10B10A2_UNORM;
					}
				}
				else if (header.ddspf.dwRBitMask && header.ddspf.dwGBitMask) {
					format = weave::vulkan::ImageFormat::R16G16_UNORM;
				}
			}
			else if (bcmps == 3) {
				format = weave::vulkan::ImageFormat::B8G8R8_UNORM;
			}
			else if (bcmps == 2) {
				format = weave::vulkan::ImageFormat::R8G8_UNORM;
			}
			else if (bcmps == 1) {
				format = weave::vulkan::ImageFormat::R8_UNORM;

			}
		}

		return format;
	}
}
/************/

using namespace weave;
using namespace graphics;

bool ImageLoader::IsCompatibleImage(std::filesystem::path const& filepath, uint32_t magic) {
	if (magic) {
		//Check for BMP header. In this case, it's only the first two bytes
		const uint32_t bmpmask = 19778U; // = 'MB'; //MB is the value of the magic number, but it could cause portability issues if used directly

		if (magic == FOURCC('D','D','S',' ') || (magic & bmpmask) == bmpmask || magic == FOURCC('«','K','T','X')) {
			return true;
		}

		//Check for TGA header. We take a wild guess and check the third byte for a valid TGA type code. The fourth byte is checked as well, as it should include a 0 on the compatible types.
		const uint32_t bytemask = 0xFF;
		int8_t typeguess = int8_t((magic & (bytemask << 16)) >> 16);
		int8_t zero = int8_t((magic & (bytemask << 24)) >> 24);
		if ((typeguess == 2 || typeguess == 10) && zero == 0) {
			return true;
		}
	}
	
	if (filepath != "") {
		//Use STB Image to check for other supported formats
		int w = 0, h = 0, comps = 0;
		if (stbi_info(reinterpret_cast<const char*>(filepath.u8string().c_str()), &w, &h, &comps) == 1 && w && h && comps)
			return true;
	}

	return false;
}

ImageData ImageLoader::Load(std::filesystem::path const& filename) {
	//Attempt loading a file with the internal DDS or TGA implementations
	ImageData imgData;

	std::fstream f(filename, std::ios::binary | std::ios::in);
	if (f.is_open()) {
		imgData = Load(f);
		f.close();
		if (!imgData.IsValid()) {
			//Attempt loading any other supported format with stb image
			imgData = ReadSTBI(reinterpret_cast<const char*>(filename.u8string().c_str()));
		}
	}

	return imgData;
}

ImageData ImageLoader::Load(std::istream &file) {
	//Check for the magic word
	uint32_t magic;
	
	file.read((char*)&magic,sizeof(magic));
	file.clear();
	file.seekg(-std::streamoff(sizeof(magic)), std::ios::cur);
	//Is it a DDS file?
	if(magic == FOURCC('D','D','S',' ')) {
		return ReadDDS(file);
	}
	//A KTX?
	else if(magic == FOURCC('«','K','T','X')) {
		return ReadKTX(file);
	}
	//A BMP?
	else if((magic & bmpMask) == bmpMask){
		return ReadBMP(file);
	}
	else {
		//Not a known file, open as TGA or die trying
		return ReadTGA(file);
	}
}

ImageData ImageLoader::ReadDDS(std::istream & file) {
	//DDS file
	DDSHeader header = {};
	DDSHeaderDXT10 headerDX10 = {};

	//Read the full basic header
	uint32_t magic;
	file.read((char*)&magic, sizeof(magic));
	file.read((char*)&header, sizeof(header));
	if(header.ddspf.dwFourCC == FOURCC('D','X','1','0')) {
		//Read the extended DX10 header
		file.read((char*)&headerDX10, sizeof(headerDX10));
	}

	//Set the basic information
	ImageData img;
	img.width = header.dwWidth;
	img.height = header.dwHeight;
	img.depth = 1;
	img.compCount = header.ddspf.dwRGBBitCount / 8;
	img.compByteSize = img.compCount ? 1 : 16;
	img.layerCount = ((header.dwCaps2 == DDSCAPS2_FULLCUBEMAP) ? 6 : 1);
	img.mipmapCount = std::max(header.dwMipMapCount, 1u);

	//Create buffers
	uint32_t bytesize = img.GetFullByteSize();
	img.data.resize(bytesize);

	//Read data
	for (uint32_t j = 0; j < img.layerCount; ++j) {
		for (uint32_t i = 0; i < img.mipmapCount; ++i) {
			bytesize = img.GetByteSize(i);
			uint8_t* mipmap = img.Surface(j, i).data.data();
			file.read((char*)mipmap, bytesize);
		}
	}

	//Set the correct image format
	img.format = GetFormatFromDDS(header, headerDX10);

	//BC1 images can have alpha, but the DDS container does not indicate such difference. 
	//The trick is to compare values on the blocks until we find a block with alpha. 
	//This is slow and BC1 with alpha is unlikely to be used, so we gamble it and just check the first values
	if (img.format == weave::vulkan::ImageFormat::BC1_RGB_UNORM_BLOCK) {
		img.compByteSize = 8;
		auto* data = reinterpret_cast<uint16_t const *>(img.GetSurface(0, 0).data.data());
		if (data[0] < data[1]) {
			img.format = weave::vulkan::ImageFormat::BC1_RGBA_UNORM_BLOCK;
		}
	}
	
	return img;
}

ImageData ImageLoader::ReadBMP(std::istream &file) {
	BMPHeader header = {};
	std::streamoff fpos = file.tellg();

	file.read((char*)&(header.h1), 14);

	if(header.h1.type != bmpMask) {  
		file.clear();
		file.seekg(fpos,std::ios::beg);
		return {}; //Not a BMP
	}
		
	file.read((char*)&(header.h2),40);
	if(header.h2.bitsperpixel != 24 && header.h2.bitsperpixel != 32) {
		file.clear();
		file.seekg(fpos,std::ios::beg);
		return {}; //It's a BMP but it's not supported
	}

	ImageData img;
	img.width  = header.h2.width;		
	img.height = header.h2.height;
	img.depth = 1;
	img.compCount = header.h2.bitsperpixel / 8;
	img.compByteSize = 1;
	img.layerCount = 1;
	img.mipmapCount = 1;

	uint32_t fileRowSize = ((header.h2.width * header.h2.bitsperpixel + 31) / 32) * 4;
	uint32_t realRowSize = img.width * img.compCount;
	img.data.resize(img.width * img.height * img.compCount);

	for(uint32_t row = 0; row < img.height; ++row) {
		//Read the useful data
		file.read((char*)img.data.data(), realRowSize);
		//Discard the padded data
		file.ignore(fileRowSize - realRowSize);
	}

	//Set format
	if (img.compCount == 4) {
		img.format = weave::vulkan::ImageFormat::R8G8B8A8_UNORM;
	}
	else if (img.compCount == 3) {
		img.format = weave::vulkan::ImageFormat::R8G8B8_UNORM;
	}
	else if (img.compCount == 2) {
		img.format = weave::vulkan::ImageFormat::R8G8_UNORM;
	}
	else if (img.compCount == 1) {
		img.format = weave::vulkan::ImageFormat::R8_UNORM;
	}
		
	return img;
}

ImageData ImageLoader::ReadTGA(std::istream &file) {
	TGAHeader header;	
	std::streamoff fpos = file.tellg();

	file.read((char *)&header, sizeof(header));
	
	if( (header.datatype != 2 && header.datatype != 10) || (header.bitsperpixel != 24 && header.bitsperpixel != 32 )) {
		file.clear();
		file.seekg(fpos,std::ios::beg);
		return {}; //Unsuported file type. Might not even be a TGA file (TGAs have no magic number)
	}
	
	ImageData img;
	img.width  = header.width;
	img.height = header.height;
	img.depth = 1;
	img.compCount = (header.bitsperpixel)/8;
	img.compByteSize = 1;
	img.layerCount = 1;
	img.mipmapCount = 1;

	img.data.resize(img.width * img.height * img.compCount);
	
	//Extra header information, we read and discard
	if(header.identlength > 0) {
		file.ignore(header.identlength);
	}

	//Datatype 2 is an uncompressed TGA file, just read and finish
	if(header.datatype == 2) {
		file.read((char*)img.data.data(), img.data.size());
	}

	/*
	Datatype 10 is an RLE compressed format.
	(Run Lenght Enconded) requiers unpacking.
	Every packet has a 1 byte header and a variable body. Two types of packets: RAW and RLE
	RAW -> first header bit to 0. Next 7 bits = number of pixels to read until next packet
	RLE -> first bit to 1. Next 7 = amount of times to repeat the next read pixel (read one, clone it)
	Important note: The amounts specified by the 7 bits are from 1 to 128, so +1 must be added
	*/
	else {
		unsigned char headbyte;
		unsigned char pixel[4];
		uint32_t j=0;
		uint32_t end = img.width * img.height * img.compCount;
		auto data = img.data.data();

		while(j < end) {
			file.read((char*)&headbyte,1);
			
			bool rle = ((headbyte & 0x80)==0x80);
	
			headbyte = (headbyte & 0x7F)+1;

			if(rle)
				file.read((char*)pixel, img.compCount);

			for (int k=0; k < headbyte; k++){
				if(!rle)
					file.read((char*)pixel, img.compCount);
				//Swap R&B
				data[j]   = pixel[0];
				data[j+1] = pixel[1];
				data[j+2] = pixel[2];
				if (img.compCount ==4)
					data[j+3] = pixel[3];
				j += img.compCount;
			}
		}
	}

	//TGAs may be fliped on their Y axis so flip the image back
	//This is indicated by bit 5. Bit 4 should indicate a flip on the X axis but this isn't implemented yet
	if(!(header.info & 32)) {
		img.FlipVertical();
	}

	//Set format
	if (img.compCount == 4) {
		img.format = weave::vulkan::ImageFormat::B8G8R8A8_UNORM;
	}
	else if (img.compCount == 3) {
		img.format = weave::vulkan::ImageFormat::B8G8R8_UNORM;
	}
	else if (img.compCount == 2) {
		img.format = weave::vulkan::ImageFormat::R8G8_UNORM;
	}
	else if (img.compCount == 1) {
		img.format = weave::vulkan::ImageFormat::R8_UNORM;
	}

	return img;
}

ImageData ImageLoader::ReadKTX(std::istream & file) {
	//KTX file definition: https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/
	//Read full header data
	KTXHeader header;
	file.read((char*)&header, sizeof(header));
	header.numberOfArrayElements = std::max(1u, header.numberOfArrayElements);

	//Check endianness of the header
	bool swapEndian = (header.endianness == 0x01020304);
	if(swapEndian) {
		//Header must be converted
		SwapEndian(reinterpret_cast<uint32_t*>(&header), sizeof(KTXHeader) / sizeof(uint32_t));
	}

	ImageData img;
	img.format = header.glFormat
		? weave::vulkan::vkGetFormatFromOpenGLFormat(static_cast<weave::opengl::GlFormat>(header.glFormat), static_cast<weave::opengl::GlFormat>(header.glType))
		: weave::vulkan::vkGetFormatFromOpenGLInternalFormat(static_cast<weave::opengl::GlFormat>(header.glInternalFormat));
	img.width = std::max(header.pixelWidth, 1u);
	img.height = std::max(header.pixelHeight, 1u);
	img.depth = std::max(header.pixelDepth, 1u);
	img.layerCount = header.numberOfFaces * header.numberOfArrayElements;
	img.mipmapCount = header.numberOfMipmapLevels;
	
	weave::vulkan::FormatSize formatSize = weave::vulkan::vkGetFormatSize(img.format);
	if (header.glFormat != 0) {
		img.compByteSize = header.glTypeSize;
		img.compCount = (formatSize.blockSizeInBits / 8) / img.compByteSize;
	}
	else {
		img.compByteSize = formatSize.blockSizeInBits / 8;
		img.compCount = 0;
	}
	//Compressed file
	if(header.glFormat == 0) {
		if (img.format == weave::vulkan::ImageFormat::BC1_RGB_UNORM_BLOCK ||
			img.format == weave::vulkan::ImageFormat::BC1_RGB_SRGB_BLOCK ||
			img.format == weave::vulkan::ImageFormat::BC1_RGBA_UNORM_BLOCK ||
			img.format == weave::vulkan::ImageFormat::BC1_RGBA_SRGB_BLOCK) {
			
			img.compByteSize = 8;
		}
	}

	//Reserve space
	uint32_t bytesize = img.GetFullByteSize();
	img.data.resize(bytesize);

	//Skip key/value data
	file.ignore(header.bytesOfKeyValueData);

	//Read the data
	for(uint32_t level = 0; level < header.numberOfMipmapLevels; ++level) {
		//Read the image size for this level
		uint32_t imgSize = 0;
		file.read((char*)&imgSize, sizeof(uint32_t));
		if(swapEndian)
			SwapEndian(&imgSize, 1);
		imgSize = (imgSize + 3) & ~3u; //Size rounded to the next multiple of 4 because the KTX files are 4 byte aligned

		//Go through the arrays and faces to compose the actual layer number
		for(uint32_t arrayPos = 0; arrayPos < header.numberOfArrayElements; ++arrayPos) {
			for(uint32_t facePos = 0; facePos < header.numberOfFaces; ++facePos) {
				uint32_t surface = arrayPos * facePos;
				auto *dataPtr = img.Surface(surface, level).data.data();

				//Read the image data
				file.read((char*)dataPtr, imgSize);
				//Endian fix
				if(swapEndian && header.glTypeSize == 2) {
					SwapEndian((uint16_t*)dataPtr, imgSize / 2);
				}
				else if(swapEndian && header.glTypeSize == 4) {
					SwapEndian((uint32_t*)dataPtr, imgSize / 4);
				}
			}
		}
	}


	return img;
}

//STBI external loader support for other formats
ImageData ImageLoader::ReadSTBI(char const * const fname) {
	ImageData img;

	int w = 0, h = 0, comps = 0;
	if (!stbi_info(fname, &w, &h, &comps)) {
		return img;
	}

	int targetComps = (comps == 3 ? 4 : comps);
	auto *data = stbi_load(fname, &w, &h, &comps, targetComps);
	if(data) {
		img.width = static_cast<uint32_t>(w);
		img.height = static_cast<uint32_t>(h);
		img.depth = 1;
		img.compCount = static_cast<uint32_t>(targetComps);
		img.compByteSize = 1;
		img.layerCount = 1;
		img.mipmapCount = 1;

		if (img.compCount == 4) {
			img.format = weave::vulkan::ImageFormat::R8G8B8A8_UNORM;
		}
		else if (img.compCount == 3) {
			img.format = weave::vulkan::ImageFormat::R8G8B8_UNORM;
		}
		else if (img.compCount == 2) {
			img.format = weave::vulkan::ImageFormat::R8G8_UNORM;
		}
		else if (img.compCount == 1) {
			img.format = weave::vulkan::ImageFormat::R8_UNORM;
		}

		img.data.assign(data, data + img.width * img.height * img.compCount);
		STBI_FREE(data);
	}

	return img;
}

void ImageLoader::WriteTGA(uint32_t width, uint32_t height, uint32_t bits, uint8_t *data, std::filesystem::path const &filepath) {
	TGAHeader header;
	//Fill in the header data
	memset(&header, 0, sizeof(header));
	header.datatype = 2;
	header.bitsperpixel = uint8_t(bits);
	header.width = uint16_t(width);
	header.height = uint16_t(height);

	//Write the data
	std::ofstream file(filepath, std::ios::binary | std::ios::out);
	file.write((char*)&header, sizeof(header));
	file.write((char*)data, width*height*bits/8);

	file.close();
}
